/**
 * Didar B2B - Deterministic Initial Gold Product Taxonomy Seed
 * Authoritative 100-Node Dataset governed by PRODUCT-TAXONOMY-SEED.md
 * Hierarchy: 5 Main Categories (Level 1) -> 21 Product Categories (Level 2) -> 74 Leaf Subcategories (Level 3) = Exactly 100 Nodes
 */

export interface TaxonomySeedNode {
  id: string;
  parentId: string | null;
  level: number;
  code: string;
  nameFa: string;
  nameEn: string;
  descriptionFa: string;
  sortOrder: number;
}

export const DETERMINISTIC_TAXONOMY_100_NODES: TaxonomySeedNode[] = [
  // =========================================================================
  // LEVEL 1: 5 MAIN CATEGORIES (شاخه اصلی)
  // =========================================================================
  {
    id: 'cat_main_body_jewelry',
    parentId: null,
    level: 1,
    code: 'body-jewelry',
    nameFa: 'زیورآلات بدنی',
    nameEn: 'Body Jewelry',
    descriptionFa: 'کلیه زیورآلات و مصنوعات ساخته‌شده طلایی قابل استفاده روی بدن',
    sortOrder: 1,
  },
  {
    id: 'cat_main_investment',
    parentId: null,
    level: 1,
    code: 'investment',
    nameFa: 'سرمایه‌ای',
    nameEn: 'Investment & Bullion',
    descriptionFa: 'شمش‌های استاندارد ۲۴ عیار، مسکوکات بانکی و قطعات سرمایه‌گذاری طلا',
    sortOrder: 2,
  },
  {
    id: 'cat_main_clothing_jewelry',
    parentId: null,
    level: 1,
    code: 'clothing-jewelry',
    nameFa: 'زیورآلات لباس',
    nameEn: 'Clothing Jewelry',
    descriptionFa: 'اکسسوری‌ها، سنجاق سینه، دکمه سردست و یراق‌آلات طلایی لباس',
    sortOrder: 3,
  },
  {
    id: 'cat_main_hair_accessories',
    parentId: null,
    level: 1,
    code: 'hair-accessories',
    nameFa: 'زیورآلات سر و مو',
    nameEn: 'Hair & Head Accessories',
    descriptionFa: 'تل، گیره مو، سنجاق و آویزهای پیشانی تمام‌طلا بدون جواهر',
    sortOrder: 4,
  },
  {
    id: 'cat_main_conceptual_custom',
    parentId: null,
    level: 1,
    code: 'conceptual-custom',
    nameFa: 'زیورآلات خاص و مفهومی',
    nameEn: 'Conceptual & Custom',
    descriptionFa: 'طراحی‌های مفهومی، نمادین، سفارشی‌سازی‌شده و قطعات تک‌نسخه گالری',
    sortOrder: 5,
  },

  // =========================================================================
  // LEVEL 2: 21 PRODUCT CATEGORIES (نوع زیورآلات)
  // =========================================================================
  // Under زیورآلات بدنی (10 Categories)
  {
    id: 'cat_type_ring',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'ring',
    nameFa: 'انگشتر',
    nameEn: 'Ring',
    descriptionFa: 'انواع انگشتر طلای مردانه، زنانه، بدون نگین و طرح‌های مدرن',
    sortOrder: 1,
  },
  {
    id: 'cat_type_earring',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'earring',
    nameFa: 'گوشواره',
    nameEn: 'Earring',
    descriptionFa: 'انواع گوشواره میخی، حلقه‌ای، آویزی، کلیپ‌دار و بخیه‌ای',
    sortOrder: 2,
  },
  {
    id: 'cat_type_necklace',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'necklace',
    nameFa: 'گردنبند',
    nameEn: 'Necklace',
    descriptionFa: 'انواع گردنبند، زنجیر، طوق و چوکر طلایی بدون نگین',
    sortOrder: 3,
  },
  {
    id: 'cat_type_bracelet',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'bracelet',
    nameFa: 'دستبند',
    nameEn: 'Bracelet',
    descriptionFa: 'انواع دستبند زنجیری، بافت‌دار و کاف طلایی',
    sortOrder: 4,
  },
  {
    id: 'cat_type_bangle',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'bangle',
    nameFa: 'النگو',
    nameEn: 'Bangle',
    descriptionFa: 'انواع النگوهای ساده، تراش‌خورده، پهن، باریک و سنتی',
    sortOrder: 5,
  },
  {
    id: 'cat_type_anklet',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'anklet',
    nameFa: 'پابند',
    nameEn: 'Anklet',
    descriptionFa: 'انواع پابند زنجیری، لایه‌ای و مینیمال طلا',
    sortOrder: 6,
  },
  {
    id: 'cat_type_body_piercing',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'body-piercing',
    nameFa: 'زیورآلات بدن و پیرسینگ',
    nameEn: 'Body Piercing',
    descriptionFa: 'پیرسینگ گوش، بینی، ناف و لب/ابرو تمام‌طلا بدون نگین',
    sortOrder: 7,
  },
  {
    id: 'cat_type_pendant',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'pendant',
    nameFa: 'آویز و پلاک',
    nameEn: 'Pendant & Medallion',
    descriptionFa: 'انواع پلاک اسم، نماد، مدرن و مینیمال بدون سنگ',
    sortOrder: 8,
  },
  {
    id: 'cat_type_chain',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'chain',
    nameFa: 'زنجیر طلا',
    nameEn: 'Chain',
    descriptionFa: 'بافت‌های مختلف زنجیر طلا (باکس، طنابی، فیگارو، کابل، ونیزی، مار)',
    sortOrder: 9,
  },
  {
    id: 'cat_type_jewelry_sets',
    parentId: 'cat_main_body_jewelry',
    level: 2,
    code: 'jewelry-sets',
    nameFa: 'ست و نیم‌ست طلا',
    nameEn: 'Jewelry Sets',
    descriptionFa: 'ست کامل، نیم‌ست کلاسیک، ست سه‌تکه و مینیمال بدون نگین',
    sortOrder: 10,
  },

  // Under سرمایه‌ای (3 Categories)
  {
    id: 'cat_type_bullion_coins',
    parentId: 'cat_main_investment',
    level: 2,
    code: 'bullion-coins',
    nameFa: 'شمش و مسکوکات طلا',
    nameEn: 'Bullion & Coins',
    descriptionFa: 'شمش‌های رسمی استاندارد، سکه بانکی و شمش‌های برنددار معتبر',
    sortOrder: 11,
  },
  {
    id: 'cat_type_melted_scrap',
    parentId: 'cat_main_investment',
    level: 2,
    code: 'melted-scrap',
    nameFa: 'طلای آب‌شده و متفرقه',
    nameEn: 'Melted & Scrap Gold',
    descriptionFa: 'مفتول، شمش کارگاهی و طلای آب‌شده استاندارد آزمایشگاهی',
    sortOrder: 12,
  },
  {
    id: 'cat_type_digital_certificates',
    parentId: 'cat_main_investment',
    level: 2,
    code: 'digital-certificates',
    nameFa: 'گواهی سپرده طلا',
    nameEn: 'Gold Deposit Certificates',
    descriptionFa: 'گواهی‌های استاندارد سپرده طلا و شمش خزانه‌داری بورس کالا',
    sortOrder: 13,
  },

  // Under زیورآلات لباس (3 Categories)
  {
    id: 'cat_type_brooch',
    parentId: 'cat_main_clothing_jewelry',
    level: 2,
    code: 'brooch',
    nameFa: 'سنجاق سینه و گل‌سینه',
    nameEn: 'Brooch',
    descriptionFa: 'سنجاق سینه ساده، تراش‌خورده، فانتزی و سنجاق روسری طلا',
    sortOrder: 14,
  },
  {
    id: 'cat_type_cufflinks_tie',
    parentId: 'cat_main_clothing_jewelry',
    level: 2,
    code: 'cufflinks-tie',
    nameFa: 'دکمه سردست و گیره کراوات',
    nameEn: 'Cufflinks & Tie Clips',
    descriptionFa: 'دکمه سردست ساده و حکاکی‌دار، گیره کراوات و ست رسمی مردانه',
    sortOrder: 15,
  },
  {
    id: 'cat_type_garment_buttons',
    parentId: 'cat_main_clothing_jewelry',
    level: 2,
    code: 'garment-buttons',
    nameFa: 'دکمه و یراق‌آلات لباس',
    nameEn: 'Garment Buttons & Hardware',
    descriptionFa: 'دکمه‌های کتی تمام‌طلا و یراق‌آلات البسه فاخر بدون سنگ',
    sortOrder: 16,
  },

  // Under زیورآلات سر و مو (2 Categories)
  {
    id: 'cat_type_hair_accessories',
    parentId: 'cat_main_hair_accessories',
    level: 2,
    code: 'hair-accessories-type',
    nameFa: 'اکسسوری‌های مو',
    nameEn: 'Hair Accessories',
    descriptionFa: 'تل طلا، گیره مو ساده، شانه تزئینی و سنجاق مو',
    sortOrder: 17,
  },
  {
    id: 'cat_type_forehead_chains',
    parentId: 'cat_main_hair_accessories',
    level: 2,
    code: 'forehead-chains',
    nameFa: 'زنجیر پیشانی و زیور سر',
    nameEn: 'Forehead Chains',
    descriptionFa: 'آویزهای پیشانی و زیورآلات سر سنتی و مدرن',
    sortOrder: 18,
  },

  // Under زیورآلات خاص و مفهومی (3 Categories)
  {
    id: 'cat_type_conceptual_jewelry',
    parentId: 'cat_main_conceptual_custom',
    level: 2,
    code: 'conceptual-jewelry',
    nameFa: 'زیور مفهومی و نمادین',
    nameEn: 'Conceptual Jewelry',
    descriptionFa: 'زیورآلات الهام‌گرفته از مفاهیم فلسفی، فرهنگی و معماری',
    sortOrder: 19,
  },
  {
    id: 'cat_type_custom_design',
    parentId: 'cat_main_conceptual_custom',
    level: 2,
    code: 'custom-design',
    nameFa: 'طراحی شخصی‌سازی‌شده',
    nameEn: 'Custom Design',
    descriptionFa: 'زیورآلات ثبت خاطره، اثر انگشت، تاریخ و نماد اختصاصی مشتری',
    sortOrder: 20,
  },
  {
    id: 'cat_type_artistic_gallery',
    parentId: 'cat_main_conceptual_custom',
    level: 2,
    code: 'artistic-gallery',
    nameFa: 'زیور گالری‌پسند و هنری',
    nameEn: 'Artistic & Gallery Jewelry',
    descriptionFa: 'آثار تک‌نسخه طراحان هنری طلا با کاربرد غیرمعمول و الهام از طبیعت',
    sortOrder: 21,
  },

  // =========================================================================
  // LEVEL 3: 74 LEAF SUBCATEGORIES (زیرشاخه‌ها)
  // =========================================================================
  // Under انگشتر (cat_type_ring) - 7 subcategories
  {
    id: 'cat_sub_plain_ring',
    parentId: 'cat_type_ring',
    level: 3,
    code: 'plain-ring',
    nameFa: 'انگشتر ساده',
    nameEn: 'Plain Ring',
    descriptionFa: 'حلقه با سطح کاملاً ساده، فاقد هرگونه تزئین یا نقش‌ونگار',
    sortOrder: 1,
  },
  {
    id: 'cat_sub_wide_band_ring',
    parentId: 'cat_type_ring',
    level: 3,
    code: 'wide-band-ring',
    nameFa: 'انگشتر پهن',
    nameEn: 'Wide Band Ring',
    descriptionFa: 'انگشترهایی با عرض زیاد، اغلب مناسب استایل رسمی یا مدرن',
    sortOrder: 2,
  },
  {
    id: 'cat_sub_slim_ring',
    parentId: 'cat_type_ring',
    level: 3,
    code: 'slim-ring',
    nameFa: 'انگشتر باریک',
    nameEn: 'Slim Ring',
    descriptionFa: 'مدل‌های ظریف، مناسب برای لایه‌سازی یا استفاده چندتایی',
    sortOrder: 3,
  },
  {
    id: 'cat_sub_textured_ring',
    parentId: 'cat_type_ring',
    level: 3,
    code: 'textured-engraved-ring',
    nameFa: 'انگشتر تراش‌خورده / حکاکی‌دار',
    nameEn: 'Textured / Engraved Ring',
    descriptionFa: 'بافت‌دار، چکش‌کاری‌شده، تراش کلاسیک، حکاکی سنتی یا مدرن',
    sortOrder: 4,
  },
  {
    id: 'cat_sub_open_ring',
    parentId: 'cat_type_ring',
    level: 3,
    code: 'open-ring',
    nameFa: 'انگشتر باز',
    nameEn: 'Open Ring',
    descriptionFa: 'مدل‌هایی که دو سرشان به هم نمی‌رسد، قابلیت تنظیم سایز دارند',
    sortOrder: 5,
  },
  {
    id: 'cat_sub_plain_wedding_band',
    parentId: 'cat_type_ring',
    level: 3,
    code: 'plain-wedding-band',
    nameFa: 'حلقه ازدواج بدون نگین',
    nameEn: 'Plain Wedding Band',
    descriptionFa: 'حلقه‌ی کاملاً طلایی سنتی یا مدرن، بدون سنگ یا نگین',
    sortOrder: 6,
  },
  {
    id: 'cat_sub_two_tone_ring',
    parentId: 'cat_type_ring',
    level: 3,
    code: 'two-tone-ring',
    nameFa: 'انگشتر ترکیبی دو یا سه‌رنگ',
    nameEn: 'Two / Three Tone Ring',
    descriptionFa: 'استفاده از دو یا سه رنگ طلا (زرد، سفید، رزگلد) در یک حلقه',
    sortOrder: 7,
  },

  // Under گوشواره (cat_type_earring) - 6 subcategories
  {
    id: 'cat_sub_plain_stud_earring',
    parentId: 'cat_type_earring',
    level: 3,
    code: 'plain-stud-earring',
    nameFa: 'گوشواره میخی ساده',
    nameEn: 'Plain Stud Earring',
    descriptionFa: 'میخ یا گلوله طلایی کوچک، کاملاً ساده و مینیمال مناسب روزمره',
    sortOrder: 8,
  },
  {
    id: 'cat_sub_plain_hoop_earring',
    parentId: 'cat_type_earring',
    level: 3,
    code: 'plain-hoop-earring',
    nameFa: 'گوشواره حلقه‌ای ساده',
    nameEn: 'Plain Hoop Earring',
    descriptionFa: 'حلقه‌های گرد یا بیضی در اندازه‌های مختلف، بدون تزئین اضافه',
    sortOrder: 9,
  },
  {
    id: 'cat_sub_plain_drop_earring',
    parentId: 'cat_type_earring',
    level: 3,
    code: 'plain-drop-earring',
    nameFa: 'گوشواره آویزی ساده',
    nameEn: 'Plain Drop Earring',
    descriptionFa: 'یک تکه طلایی آویزان از گوش، بدون هرگونه نگین یا سنگ',
    sortOrder: 10,
  },
  {
    id: 'cat_sub_plain_clip_earring',
    parentId: 'cat_type_earring',
    level: 3,
    code: 'plain-clip-earring',
    nameFa: 'گوشواره چسبان / کلیپ‌دار ساده',
    nameEn: 'Plain Clip-on Earring',
    descriptionFa: 'بدون نیاز به سوراخ گوش، کاملاً طلایی و ساده',
    sortOrder: 11,
  },
  {
    id: 'cat_sub_plain_threader_earring',
    parentId: 'cat_type_earring',
    level: 3,
    code: 'plain-threader-earring',
    nameFa: 'گوشواره بخیه‌ای ساده',
    nameEn: 'Plain Threader Earring',
    descriptionFa: 'زنجیر یا میله طلایی نازک ردشونده از گوش؛ کاملاً ساده و مدرن',
    sortOrder: 12,
  },
  {
    id: 'cat_sub_geometric_earring',
    parentId: 'cat_type_earring',
    level: 3,
    code: 'geometric-earring',
    nameFa: 'گوشواره هندسی فرم‌دار',
    nameEn: 'Geometric Shape Earring',
    descriptionFa: 'فرم‌های هندسی مثل مثلث، مربع یا دایره، تماماً طلا',
    sortOrder: 13,
  },

  // Under گردنبند (cat_type_necklace) - 6 subcategories
  {
    id: 'cat_sub_plain_chain_necklace',
    parentId: 'cat_type_necklace',
    level: 3,
    code: 'plain-chain-necklace',
    nameFa: 'گردنبند زنجیری ساده',
    nameEn: 'Plain Chain Necklace',
    descriptionFa: 'زنجیر طلایی ساده با بافت‌های مختلف بدون پلاک یا آویز',
    sortOrder: 14,
  },
  {
    id: 'cat_sub_plain_gold_choker',
    parentId: 'cat_type_necklace',
    level: 3,
    code: 'plain-gold-choker',
    nameFa: 'چوکر طلایی ساده',
    nameEn: 'Plain Gold Choker',
    descriptionFa: 'گردنبند کوتاه و چسبان به گردن، کاملاً طلایی و مینیمال',
    sortOrder: 15,
  },
  {
    id: 'cat_sub_plain_collar_necklace',
    parentId: 'cat_type_necklace',
    level: 3,
    code: 'plain-collar-necklace',
    nameFa: 'گردنبند طوقی ساده',
    nameEn: 'Plain Collar Necklace',
    descriptionFa: 'مدل طوقی کلاسیک یا مدرن نشسته روی ترقوه، سطح صاف یا بافت‌دار',
    sortOrder: 16,
  },
  {
    id: 'cat_sub_plain_layered_necklace',
    parentId: 'cat_type_necklace',
    level: 3,
    code: 'plain-layered-necklace',
    nameFa: 'گردنبند لایه‌ای ساده',
    nameEn: 'Plain Layered Necklace',
    descriptionFa: 'ترکیب چند زنجیر طلایی با طول‌های مختلف بدون آویز اضافی',
    sortOrder: 17,
  },
  {
    id: 'cat_sub_modern_wide_necklace',
    parentId: 'cat_type_necklace',
    level: 3,
    code: 'modern-wide-necklace',
    nameFa: 'گردنبند پهن و مدرن',
    nameEn: 'Modern Wide Necklace',
    descriptionFa: 'گردنبندهای پهن با فرم معمارانه، کاملاً طلایی و بدون سنگ',
    sortOrder: 18,
  },
  {
    id: 'cat_sub_minimal_necklace',
    parentId: 'cat_type_necklace',
    level: 3,
    code: 'minimal-necklace',
    nameFa: 'گردنبند مینیمال',
    nameEn: 'Minimal Necklace',
    descriptionFa: 'فرم‌های خطی و هندسی مینیمال، مناسب استایل روزمره',
    sortOrder: 19,
  },

  // Under دستبند (cat_type_bracelet) - 6 subcategories
  {
    id: 'cat_sub_plain_chain_bracelet',
    parentId: 'cat_type_bracelet',
    level: 3,
    code: 'plain-chain-bracelet',
    nameFa: 'دستبند زنجیری ساده',
    nameEn: 'Plain Chain Bracelet',
    descriptionFa: 'دستبند با زنجیر طلایی در بافت‌های مختلف ونیزی، فیگارو و طنابی',
    sortOrder: 20,
  },
  {
    id: 'cat_sub_textured_bracelet',
    parentId: 'cat_type_bracelet',
    level: 3,
    code: 'textured-bracelet',
    nameFa: 'دستبند بافت‌دار',
    nameEn: 'Textured / Braided Bracelet',
    descriptionFa: 'مدل‌های بافت خاص چرخشی، طنابی یا موجی تمام‌طلا',
    sortOrder: 21,
  },
  {
    id: 'cat_sub_cuff_bracelet',
    parentId: 'cat_type_bracelet',
    level: 3,
    code: 'cuff-bracelet',
    nameFa: 'دستبند پهن کاف',
    nameEn: 'Wide Cuff Bracelet',
    descriptionFa: 'دستبند پهن باز و بدون قفل، صلب و معمارانه',
    sortOrder: 22,
  },
  {
    id: 'cat_sub_slim_bracelet',
    parentId: 'cat_type_bracelet',
    level: 3,
    code: 'slim-bracelet',
    nameFa: 'دستبند باریک مینیمال',
    nameEn: 'Slim Minimal Bracelet',
    descriptionFa: 'مدل‌های بسیار ظریف و ساده مناسب لایه‌سازی روزمره',
    sortOrder: 23,
  },
  {
    id: 'cat_sub_two_tone_bracelet',
    parentId: 'cat_type_bracelet',
    level: 3,
    code: 'two-tone-bracelet',
    nameFa: 'دستبند ترکیبی چندرنگ',
    nameEn: 'Two / Three Tone Bracelet',
    descriptionFa: 'ترکیب طلای زرد، سفید و رزگلد در یک دستبند بدون نگین',
    sortOrder: 24,
  },
  {
    id: 'cat_sub_open_bracelet',
    parentId: 'cat_type_bracelet',
    level: 3,
    code: 'open-bracelet',
    nameFa: 'دستبند باز قابل تنظیم',
    nameEn: 'Open Adjustable Bracelet',
    descriptionFa: 'مدل‌های باز و انعطاف‌پذیر با قابلیت تنظیم سایز روی مچ',
    sortOrder: 25,
  },

  // Under النگو (cat_type_bangle) - 6 subcategories
  {
    id: 'cat_sub_plain_bangle',
    parentId: 'cat_type_bangle',
    level: 3,
    code: 'plain-bangle',
    nameFa: 'النگوی ساده',
    nameEn: 'Plain Bangle',
    descriptionFa: 'حلقه طلایی با سطح کاملاً ساده در قطرها و ضخامت‌های استاندارد',
    sortOrder: 26,
  },
  {
    id: 'cat_sub_textured_bangle',
    parentId: 'cat_type_bangle',
    level: 3,
    code: 'textured-bangle',
    nameFa: 'النگوی تراش‌خورده',
    nameEn: 'Textured Bangle',
    descriptionFa: 'سطح دارای تراش، حکاکی یا چکش‌کاری بدون نگین',
    sortOrder: 27,
  },
  {
    id: 'cat_sub_wide_bangle',
    parentId: 'cat_type_bangle',
    level: 3,
    code: 'wide-bangle',
    nameFa: 'النگوی پهن',
    nameEn: 'Wide Bangle',
    descriptionFa: 'مدل‌های النگوی پهن مجلسی با جلوه بصری بالا',
    sortOrder: 28,
  },
  {
    id: 'cat_sub_slim_bangle',
    parentId: 'cat_type_bangle',
    level: 3,
    code: 'slim-bangle',
    nameFa: 'النگوی باریک',
    nameEn: 'Slim Bangle',
    descriptionFa: 'مدل‌های ظریف و سبک مناسب استفاده چندتایی',
    sortOrder: 29,
  },
  {
    id: 'cat_sub_stackable_bangle',
    parentId: 'cat_type_bangle',
    level: 3,
    code: 'stackable-bangle-set',
    nameFa: 'النگوی ست لایه‌ای',
    nameEn: 'Stackable Bangle Set',
    descriptionFa: 'مجموعه چند النگوی باریک با طرح هماهنگ برای لایه‌سازی',
    sortOrder: 30,
  },
  {
    id: 'cat_sub_traditional_bangle',
    parentId: 'cat_type_bangle',
    level: 3,
    code: 'traditional-bangle',
    nameFa: 'النگوی سنتی و محلی',
    nameEn: 'Traditional Ethnic Bangle',
    descriptionFa: 'طرح‌های سنتی اقوام ایرانی کاملاً طلایی بدون نگین',
    sortOrder: 31,
  },

  // Under پابند (cat_type_anklet) - 4 subcategories
  {
    id: 'cat_sub_plain_chain_anklet',
    parentId: 'cat_type_anklet',
    level: 3,
    code: 'plain-chain-anklet',
    nameFa: 'پابند زنجیری ساده',
    nameEn: 'Plain Chain Anklet',
    descriptionFa: 'زنجیر طلایی ساده بدون آویز یا تزئین اضافه',
    sortOrder: 32,
  },
  {
    id: 'cat_sub_layered_anklet',
    parentId: 'cat_type_anklet',
    level: 3,
    code: 'layered-anklet',
    nameFa: 'پابند دولایه',
    nameEn: 'Layered Anklet',
    descriptionFa: 'دو یا چند زنجیر ساده در یک پابند تمام‌طلا',
    sortOrder: 33,
  },
  {
    id: 'cat_sub_minimal_anklet',
    parentId: 'cat_type_anklet',
    level: 3,
    code: 'minimal-anklet',
    nameFa: 'پابند مینیمال',
    nameEn: 'Minimal Anklet',
    descriptionFa: 'مدل‌های بسیار ظریف و سبک برای استفاده روزمره و فشن',
    sortOrder: 34,
  },
  {
    id: 'cat_sub_two_tone_anklet',
    parentId: 'cat_type_anklet',
    level: 3,
    code: 'two-tone-anklet',
    nameFa: 'پابند ترکیبی چندرنگ',
    nameEn: 'Two Tone Anklet',
    descriptionFa: 'ترکیب طلای زرد و سفید در یک پابند بدون نگین',
    sortOrder: 35,
  },

  // Under زیورآلات بدن و پیرسینگ (cat_type_body_piercing) - 4 subcategories
  {
    id: 'cat_sub_ear_piercing',
    parentId: 'cat_type_body_piercing',
    level: 3,
    code: 'ear-piercing',
    nameFa: 'پیرسینگ گوش ساده',
    nameEn: 'Plain Ear Piercing',
    descriptionFa: 'میخ یا حلقه طلایی ریز برای نقاط مختلف گوش بدون نگین',
    sortOrder: 36,
  },
  {
    id: 'cat_sub_nose_piercing',
    parentId: 'cat_type_body_piercing',
    level: 3,
    code: 'nose-piercing',
    nameFa: 'پیرسینگ بینی ساده',
    nameEn: 'Plain Nose Stud / Ring',
    descriptionFa: 'میخ یا حلقه طلایی ریز مخصوص بینی بدون نگین',
    sortOrder: 37,
  },
  {
    id: 'cat_sub_navel_piercing',
    parentId: 'cat_type_body_piercing',
    level: 3,
    code: 'navel-piercing',
    nameFa: 'پیرسینگ ناف ساده',
    nameEn: 'Plain Navel Piercing',
    descriptionFa: 'میله منحنی طلایی بدون آویز یا نگین با طراحی کاملاً ساده',
    sortOrder: 38,
  },
  {
    id: 'cat_sub_lip_brow_piercing',
    parentId: 'cat_type_body_piercing',
    level: 3,
    code: 'lip-brow-piercing',
    nameFa: 'پیرسینگ لب و ابرو ساده',
    nameEn: 'Plain Lip / Brow Piercing',
    descriptionFa: 'میخ یا حلقه طلایی ارگونومیک برای لب و ابرو',
    sortOrder: 39,
  },

  // Under آویز و پلاک (cat_type_pendant) - 4 subcategories
  {
    id: 'cat_sub_name_pendant',
    parentId: 'cat_type_pendant',
    level: 3,
    code: 'name-pendant',
    nameFa: 'پلاک اسم ساده',
    nameEn: 'Plain Name Pendant',
    descriptionFa: 'پلاک حروف یا اسم با خطوط کلاسیک و نستعلیق فقط از طلا',
    sortOrder: 40,
  },
  {
    id: 'cat_sub_symbol_pendant',
    parentId: 'cat_type_pendant',
    level: 3,
    code: 'symbol-pendant',
    nameFa: 'پلاک نماد و هندسی',
    nameEn: 'Symbol / Geometric Pendant',
    descriptionFa: 'نمادهای هندسی و فرهنگی (بی‌نهایت، قلب، ستاره) تمام‌طلا',
    sortOrder: 41,
  },
  {
    id: 'cat_sub_modern_pendant',
    parentId: 'cat_type_pendant',
    level: 3,
    code: 'modern-pendant',
    nameFa: 'پلاک فرم‌دار مدرن',
    nameEn: 'Modern Shaped Pendant',
    descriptionFa: 'فرم‌های معاصر، ارگانیک و فشن بدون سنگ',
    sortOrder: 42,
  },
  {
    id: 'cat_sub_minimal_pendant',
    parentId: 'cat_type_pendant',
    level: 3,
    code: 'minimal-pendant',
    nameFa: 'پلاک مینیمال',
    nameEn: 'Minimal Pendant',
    descriptionFa: 'خطوط و احجام کوچک هندسی مناسب هدیه و استفاده روزمره',
    sortOrder: 43,
  },

  // Under زنجیر طلا (cat_type_chain) - 6 subcategories
  {
    id: 'cat_sub_box_chain',
    parentId: 'cat_type_chain',
    level: 3,
    code: 'box-chain',
    nameFa: 'زنجیر باکس',
    nameEn: 'Box Chain',
    descriptionFa: 'زنجیر با بافت مکعبی و حلقه‌های مربعی منظم و مقاوم',
    sortOrder: 44,
  },
  {
    id: 'cat_sub_rope_chain',
    parentId: 'cat_type_chain',
    level: 3,
    code: 'rope-chain',
    nameFa: 'زنجیر طنابی',
    nameEn: 'Rope Chain',
    descriptionFa: 'حلقه‌های به‌هم‌تابیده شبیه طناب با درخشش بالا',
    sortOrder: 45,
  },
  {
    id: 'cat_sub_figaro_chain',
    parentId: 'cat_type_chain',
    level: 3,
    code: 'figaro-chain',
    nameFa: 'زنجیر فیگارو',
    nameEn: 'Figaro Chain',
    descriptionFa: 'ترکیب تناوبی حلقه‌های بلند و کوتاه مناسب استایل مدرن',
    sortOrder: 46,
  },
  {
    id: 'cat_sub_cable_chain',
    parentId: 'cat_type_chain',
    level: 3,
    code: 'cable-chain',
    nameFa: 'زنجیر بیضی کابل',
    nameEn: 'Cable Chain',
    descriptionFa: 'حلقه‌های بیضی متوالی منظم و کلاسیک',
    sortOrder: 47,
  },
  {
    id: 'cat_sub_snake_chain',
    parentId: 'cat_type_chain',
    level: 3,
    code: 'snake-chain',
    nameFa: 'زنجیر مار',
    nameEn: 'Snake Chain',
    descriptionFa: 'بافت پیوسته و فشرده با انعطاف بالا شبیه پوست مار',
    sortOrder: 48,
  },
  {
    id: 'cat_sub_venetian_chain',
    parentId: 'cat_type_chain',
    level: 3,
    code: 'venetian-chain',
    nameFa: 'زنجیر ونیزی',
    nameEn: 'Venetian Chain',
    descriptionFa: 'بافت مکعبی بسیار ظریف، کلاسیک و فوق‌العاده مقاوم',
    sortOrder: 49,
  },

  // Under ست و نیم‌ست طلا (cat_type_jewelry_sets) - 4 subcategories
  {
    id: 'cat_sub_full_gold_set',
    parentId: 'cat_type_jewelry_sets',
    level: 3,
    code: 'full-gold-set',
    nameFa: 'ست کامل طلا بدون نگین',
    nameEn: 'Full Gold Set',
    descriptionFa: 'مجموعه گردنبند، گوشواره، دستبند و انگشتر با طراحی یکدست',
    sortOrder: 50,
  },
  {
    id: 'cat_sub_classic_half_set',
    parentId: 'cat_type_jewelry_sets',
    level: 3,
    code: 'classic-half-set',
    nameFa: 'نیم‌ست کلاسیک',
    nameEn: 'Classic Half Set',
    descriptionFa: 'ترکیب گردنبند و گوشواره یا گردنبند و دستبند هماهنگ',
    sortOrder: 51,
  },
  {
    id: 'cat_sub_minimal_half_set',
    parentId: 'cat_type_jewelry_sets',
    level: 3,
    code: 'minimal-half-set',
    nameFa: 'نیم‌ست مینیمال',
    nameEn: 'Minimal Half Set',
    descriptionFa: 'قطعات ظریف خطی و هندسی هماهنگ برای استایل روزمره',
    sortOrder: 52,
  },
  {
    id: 'cat_sub_three_piece_set',
    parentId: 'cat_type_jewelry_sets',
    level: 3,
    code: 'three-piece-set',
    nameFa: 'ست سه‌تکه طلا',
    nameEn: 'Three-Piece Set',
    descriptionFa: 'مجموعه سه تکه شامل گردنبند، گوشواره و انگشتر تمام‌طلا',
    sortOrder: 53,
  },

  // Under شمش و مسکوکات طلا (cat_type_bullion_coins) - 5 subcategories
  {
    id: 'cat_sub_standard_bullion',
    parentId: 'cat_type_bullion_coins',
    level: 3,
    code: 'standard-bullion',
    nameFa: 'شمش استاندارد ۲۴ عیار',
    nameEn: 'Standard Bullion',
    descriptionFa: 'شمش با عیار ۹۹۹.۹ در اوزان ۱ گرم تا ۱ کیلوگرم دارای هولوگرام',
    sortOrder: 54,
  },
  {
    id: 'cat_sub_minted_gold_coin',
    parentId: 'cat_type_bullion_coins',
    level: 3,
    code: 'minted-gold-coin',
    nameFa: 'سکه طلا بانکی',
    nameEn: 'Minted Gold Coin',
    descriptionFa: 'مسکوکات رسمی ضرب بانک مرکزی (تمام، نیم، ربع و گرمی)',
    sortOrder: 55,
  },
  {
    id: 'cat_sub_commemorative_bullion',
    parentId: 'cat_type_bullion_coins',
    level: 3,
    code: 'commemorative-bullion',
    nameFa: 'شمش طرح‌دار و مناسبتی',
    nameEn: 'Commemorative Bullion',
    descriptionFa: 'شمش‌های مناسبتی و یادبود اهدایی با طراحی ویژه',
    sortOrder: 56,
  },
  {
    id: 'cat_sub_branded_bullion',
    parentId: 'cat_type_bullion_coins',
    level: 3,
    code: 'branded-bullion',
    nameFa: 'شمش برنددار جهانی',
    nameEn: 'Branded Bullion',
    descriptionFa: 'شمش‌های معتبر بین‌المللی (PAMP، Valcambi) همراه با شناسنامه',
    sortOrder: 57,
  },
  {
    id: 'cat_sub_combo_gold',
    parentId: 'cat_type_bullion_coins',
    level: 3,
    code: 'combo-gold',
    nameFa: 'شمش کارتی ترکیبی',
    nameEn: 'Combo Gold',
    descriptionFa: 'شمش‌های چندبخشی جداشونده کارتی برای پرداخت‌های خرد',
    sortOrder: 58,
  },

  // Under طلای آب‌شده و متفرقه (cat_type_melted_scrap) - 2 subcategories
  {
    id: 'cat_sub_melted_gold_bar',
    parentId: 'cat_type_melted_scrap',
    level: 3,
    code: 'melted-gold-bar',
    nameFa: 'شمش طلای آب‌شده کارگاهی',
    nameEn: 'Melted Gold Bar',
    descriptionFa: 'شمش طلای آب‌شده آزمایشگاهی همراه با شماره انگ و عیارسنجی',
    sortOrder: 59,
  },
  {
    id: 'cat_sub_scrap_karat_gold',
    parentId: 'cat_type_melted_scrap',
    level: 3,
    code: 'scrap-karat-gold',
    nameFa: 'طلای متفرقه کارگاهی',
    nameEn: 'Scrap Karat Gold',
    descriptionFa: 'ضایعات و طلای متفرقه استاندارد ۱۸ عیار جهت ذوب و ریخته‌گری',
    sortOrder: 60,
  },

  // Under گواهی سپرده طلا (cat_type_digital_certificates) - 1 subcategory
  {
    id: 'cat_sub_bourse_gold_certificate',
    parentId: 'cat_type_digital_certificates',
    level: 3,
    code: 'bourse-gold-certificate',
    nameFa: 'گواهی سپرده طلای بورس کالا',
    nameEn: 'Bourse Gold Certificate',
    descriptionFa: 'گواهی سپرده الکترونیکی شمش طلا پشتوانه‌دار خزانه بانک',
    sortOrder: 61,
  },

  // Under سنجاق سینه و گل‌سینه (cat_type_brooch) - 3 subcategories
  {
    id: 'cat_sub_plain_brooch',
    parentId: 'cat_type_brooch',
    level: 3,
    code: 'plain-brooch',
    nameFa: 'سنجاق سینه ساده',
    nameEn: 'Plain Brooch',
    descriptionFa: 'طرح تمام‌طلا با سطح براق یا مات بدون نگین و سنگ',
    sortOrder: 62,
  },
  {
    id: 'cat_sub_textured_brooch',
    parentId: 'cat_type_brooch',
    level: 3,
    code: 'textured-brooch',
    nameFa: 'سنجاق سینه تراش‌خورده',
    nameEn: 'Textured Brooch',
    descriptionFa: 'بافت خاص، حکاکی سنتی یا مدرن طرح گل و برگ تمام‌طلا',
    sortOrder: 63,
  },
  {
    id: 'cat_sub_scarf_brooch',
    parentId: 'cat_type_brooch',
    level: 3,
    code: 'scarf-brooch',
    nameFa: 'سنجاق روسری طلا',
    nameEn: 'Scarf Brooch',
    descriptionFa: 'سنجاق ایمن جهت فیکس کردن شال و روسری بدون نگین',
    sortOrder: 64,
  },

  // Under دکمه سردست و گیره کراوات (cat_type_cufflinks_tie) - 3 subcategories
  {
    id: 'cat_sub_plain_cufflinks',
    parentId: 'cat_type_cufflinks_tie',
    level: 3,
    code: 'plain-cufflinks',
    nameFa: 'دکمه سردست ساده',
    nameEn: 'Plain Cufflinks',
    descriptionFa: 'فرم‌های هندسی دایره یا مربع با پرداخت آینه‌ای براق',
    sortOrder: 65,
  },
  {
    id: 'cat_sub_engraved_cufflinks',
    parentId: 'cat_type_cufflinks_tie',
    level: 3,
    code: 'engraved-cufflinks',
    nameFa: 'دکمه سردست حکاکی‌دار',
    nameEn: 'Engraved Cufflinks',
    descriptionFa: 'حکاکی حروف اول، لوگو یا اعداد خاص روی طلای ۱۸ عیار',
    sortOrder: 66,
  },
  {
    id: 'cat_sub_plain_tie_clip',
    parentId: 'cat_type_cufflinks_tie',
    level: 3,
    code: 'plain-tie-clip',
    nameFa: 'گیره کراوات ساده',
    nameEn: 'Plain Tie Clip',
    descriptionFa: 'میله طلایی مینیمال برای کت‌وشلوار رسمی مردانه',
    sortOrder: 67,
  },

  // Under دکمه و یراق‌آلات لباس (cat_type_garment_buttons) - 1 subcategory
  {
    id: 'cat_sub_gold_blazer_buttons',
    parentId: 'cat_type_garment_buttons',
    level: 3,
    code: 'gold-blazer-buttons',
    nameFa: 'دکمه طلای کت و مانتو',
    nameEn: 'Gold Blazer Buttons',
    descriptionFa: 'ست دکمه‌های کتی تمام‌طلا ۱۸ عیار با پایه دوخت مستحکم',
    sortOrder: 68,
  },

  // Under اکسسوری‌های مو (cat_type_hair_accessories) - 3 subcategories
  {
    id: 'cat_sub_gold_headband',
    parentId: 'cat_type_hair_accessories',
    level: 3,
    code: 'gold-headband',
    nameFa: 'تل طلا',
    nameEn: 'Gold Headband',
    descriptionFa: 'تل باریک یا پهن با سطح طلایی صاف یا نقش‌دار بدون سنگ',
    sortOrder: 69,
  },
  {
    id: 'cat_sub_plain_hair_clip',
    parentId: 'cat_type_hair_accessories',
    level: 3,
    code: 'plain-hair-clip',
    nameFa: 'گیره مو ساده',
    nameEn: 'Plain Hair Clip',
    descriptionFa: 'گیره مو با فرم کلاسیک یا موجی فقط از طلا بدون نگین',
    sortOrder: 70,
  },
  {
    id: 'cat_sub_hair_pin',
    parentId: 'cat_type_hair_accessories',
    level: 3,
    code: 'hair-pin',
    nameFa: 'سنجاق مو طلا',
    nameEn: 'Hair Pin',
    descriptionFa: 'سنجاق طلایی شینیون و موهای بلند با سطح صیقلی',
    sortOrder: 71,
  },

  // Under زنجیر پیشانی و زیور سر (cat_type_forehead_chains) - 1 subcategory
  {
    id: 'cat_sub_forehead_chain',
    parentId: 'cat_type_forehead_chains',
    level: 3,
    code: 'forehead-chain',
    nameFa: 'زنجیر پیشانی سنتی',
    nameEn: 'Forehead Chain',
    descriptionFa: 'آویز طلایی ظریف پیشانی با بافت سنتی بدون نگین',
    sortOrder: 72,
  },

  // Under زیور مفهومی و نمادین (cat_type_conceptual_jewelry) - 1 subcategory
  {
    id: 'cat_sub_symbolic_conceptual',
    parentId: 'cat_type_conceptual_jewelry',
    level: 3,
    code: 'symbolic-conceptual',
    nameFa: 'زیور مفهومی نمادین',
    nameEn: 'Symbolic Conceptual Jewelry',
    descriptionFa: 'طراحی برگرفته از مفاهیم فلسفی و ادبیات کهن فارسی',
    sortOrder: 73,
  },

  // Under طراحی شخصی‌سازی‌شده و هنری (cat_type_custom_design) - 1 subcategory
  {
    id: 'cat_sub_custom_engraved_piece',
    parentId: 'cat_type_custom_design',
    level: 3,
    code: 'custom-engraved-piece',
    nameFa: 'قطعه هنری سفارشی تک‌نسخه',
    nameEn: 'Custom Engraved Art Piece',
    descriptionFa: 'زیور اختصاصی ثبت ماندگار بر پایه اثر انگشت یا دست‌نوشته',
    sortOrder: 74,
  },
];
